# Generated by Django 4.2.25 on 2025-10-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lexicon',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('freq', models.IntegerField(null=True)),
                ('num_texts', models.IntegerField(null=True)),
                ('perc_caps', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('blog', models.IntegerField(null=True)),
                ('web', models.IntegerField(null=True)),
                ('tvm', models.IntegerField(null=True)),
                ('spok', models.IntegerField(null=True)),
                ('fic', models.IntegerField(null=True)),
                ('mag', models.IntegerField(null=True)),
                ('news', models.IntegerField(null=True)),
                ('acad', models.IntegerField(null=True)),
                ('blog_pm', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('web_pm', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('tvm_pm', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('spok_pm', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('fic_pm', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('mag_pm', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('news_pm', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('acad_pm', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('apl_class', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'lexicon',
            },
        ),
        migrations.CreateModel(
            name='LookedUpWords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'looked_up_words',
            },
        ),
        migrations.CreateModel(
            name='SkipWords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'skip_words',
            },
        ),
    ]
