# Generated by Django 4.2.25 on 2025-10-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20251025_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('caps_count', models.IntegerField()),
                ('common_count', models.IntegerField()),
                ('uncommon_count', models.IntegerField()),
                ('unknown_count', models.IntegerField()),
                ('looked_up_count', models.IntegerField()),
                ('skip_count', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('payment_id', models.IntegerField()),
            ],
            options={
                'db_table': 'analyzation',
            },
        ),
    ]
