# Generated by Django 4.2.25 on 2025-10-27 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_analyzation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='analyzation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyzations', to=settings.AUTH_USER_MODEL),
        ),
    ]
