# Generated by Django 4.2.25 on 2025-10-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_analyzation_user_id_analyzation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzation',
            name='common_count',
        ),
        migrations.RemoveField(
            model_name='analyzation',
            name='skip_count',
        ),
    ]
